FORMAT: 1A
HOST: http://api.staging.qwiqer.com

# Core API V1.0

## Introduction
The Qwiqer API is organized around REST. Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, like HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients.

We support cross-origin resource sharing, allowing you to interact securely with our API from a client-side web application (though you should never expose your secret API key in any public website's client-side code). JSON is returned by all API responses, including errors, although our API libraries convert responses to appropriate language-specific objects.

To make the API as explorable as possible, accounts have test mode and live mode API keys. There is no "switch" for changing between modes, just use the appropriate key to perform a live or test transaction.

## Authentication
Authenticate your account when using the API by including your secret API key in the request. You can manage your API keys in the Dashboard. Your API keys carry many privileges, so be sure to keep them secret! Do not share your secret API keys in publicly accessible areas such GitHub, client-side code, and so forth.

Authentication to the API is performed via HTTP Basic Auth. Provide your API key as the basic auth username value. You do not need to provide a password.

If you need to authenticate via bearer auth (e.g., for a cross-origin request), use `-H "Authorization: Bearer test_BQokikJOvBiI2HlWgH4olfQ2"` instead of `-u test_BQokikJOvBiI2HlWgH4olfQ2:`.

All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.

# Group Authenticate

## Login [POST /login]
Authenticate a user

+ Request Manager login (application/json)
    + Attributes
        + auth (object)
            + email: `manager@example.com`
            + password: `defaultpassword`

+ Response 201 (application/json; charset=utf-8)
    + Attributes (object)
        + jwt: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzYzNzg1NzIsInN1YiI6MX0.5MuPNzEz9EpbZlGTOPYB99lRqjj1PubmyqvmH8hYggI` (string)

+ Request Driver login (application/json)
    + Attributes
        + auth (object)
            + email: `driver1@example.com`
            + password: `defaultpassword`

+ Response 201 (application/json; charset=utf-8)
    + Attributes (object)
        + jwt: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzYzNzg1NzIsInN1YiI6MX0.5MuPNzEz9EpbZlGTOPYB99lRqjj1PubmyqvmH8hYggI` (string)

+ Request (application/json)
    + Attributes
        + auth (object)
            + email: `not-a-user@example.com`
            + password: `defaultpassword`

+ Response 404 (text/html)

# Group Deliveries

## Collection [/deliveries]

### Retrieve all Deliveries [GET]
Returns all active deliveries.

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Delivery])

### Create Delivery [POST]
Creates a delivery.

+ Request with recipient_id (application/json)
    + Attributes
      + delivery
          + recipient_id: `2` (number)
          + pickup_at: `2016-01-01T18:00Z` (string, nullable)
          + deliver_at: `2016-01-01T19:00Z` (string)
          + instructions: `Please ring bell and wait, I am slow to answering the door. If I don’t answer within a few minutes the keysafe number is 9018. Please enter and announce loudly who you are.` (string)
          + route (Route)
          + order (Order)

+ Request with recipient data (application/json)
    + Attributes
      + delivery
          + recipient (RecipientParams)
          + pickup_at: `2016-01-01T18:00Z` (string, nullable)
          + deliver_at: `2016-01-01T19:00Z` (string)
          + instructions: `Please ring bell and wait, I am slow to answering the door. If I don’t answer within a few minutes the keysafe number is 9018. Please enter and announce loudly who you are.` (string)
          + route (Route)
          + order (Order)

+ Response 201 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include Delivery

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## Delivery [/deliveries/{id}]

### Retrieve a delivery [GET]
Returns delivery.

+ Parameters
  + id: `1` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include Delivery

+ Response 404 (application/json)
    + Attributes (NotFoundError)

### Update a delivery [PUT]
Updates a delivery.

+ Parameters
  + id: `1` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (string)
      + Include Delivery

+ Response 404 (application/json)
    + Attributes (NotFoundError)

### Delete a delivery [DELETE]
Delete a delivery.

+ Parameters
  + id: `1` (number)

+ Response 204

+ Response 404 (application/json)
    + Attributes (NotFoundError)

+ Response 401 (application/json)
    + Attributes (Unauthorized)


# Group Jobs

## Collection [/jobs]

### Retrieve all Jobs [GET]
Returns all active jobs.

+ Request (application/json)
    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzYzNzg1NzIsInN1YiI6MX0.5MuPNzEz9EpbZlGTOPYB99lRqjj1PubmyqvmH8hYggI

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Job])

## Job [/jobs/{id}]

### Retrieve a job [GET]
Returns Job.

+ Parameters
  + id: `1` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (string)
      + Include Job

## /jobs/{id}/accept

### Accept a job [POST]
Driver accepts a job.

+ Parameters
    + id: `1` (number)

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include AcceptedJob

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/start

### Start a job [POST]
Driver starts a job.

+ Parameters
    + id: `1` (number)

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include StartedJob

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/cancel

### Cancel a job [POST]
Driver cancels a job.

+ Parameters
    + id: `1` (number)

+ Request (application/json)
    + Attributes
      + driver_id: `3` (string)
      + reason: `driver_fault` (string)
      + notes: `My car is broken` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include CancelledJob

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/complete

### Complete a job [POST]
Driver completes a job.

+ Parameters
    + id: `1` (number)

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include CompletedJob

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/sign

### Sign a job [POST]
Driver signs a job.

+ Parameters
    + id: `1` (number)

+ Request (application/json)
    + Attributes
        + signature_file (object)
            + data: `data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include SignedJob

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

# Group Photos

## /jobs/{job_id}/photos

### Add a photo to a job [POST]
Driver adds a photo to a job.

+ Parameters
    + job_id: `1` (number)

+ Request (application/json)
    + Attributes
      + photo (object)
        + data: `base64:image/png...` (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + Include Photo

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

### List all photos [GET]
Returns a list of job's photos.

+ Parameters
    + job_id: `1` (number)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Photo])

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

# Group Comments

## /jobs/{job_id}/comments

### List all comments [GET]
Returns a list of job's comments.

+ Parameters
    + job_id: `1` (number)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Comment])

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

### Add a comment to a job [POST]
Driver adds a comment to a job.

+ Parameters
    + job_id: `1` (number)

+ Request (application/json)
    + Attributes (Comment)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
      + id: `1` (number)
      + Include Comment

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

# Group Drivers

## Collection [/drivers]

### List all drivers [GET]
Returns all available drivers.
"Available" means a driver signed up and uses mobile app despite the current status: online or offline.

+ Request (application/json)
    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzYzNzg1NzIsInN1YiI6MX0.5MuPNzEz9EpbZlGTOPYB99lRqjj1PubmyqvmH8hYggI

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Driver])

### Pending - Invite a driver [POST]
Creates a driver.

+ Request (application/json)
    + Attributes
      + Include InviteDriverParams

+ Response 201 (application/json; charset=utf-8)

+ Response 422 (application/json; charset=utf-8)
    + Attributes (UnprocessableEntityError)

## /drivers/{id}

### Retrieve a driver [GET]
Returns a driver.

+ Parameters
  + id: `3` (number)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Driver)

+ Response 404 (application/json)
    + Attributes (NotFoundError)

# Data Structures

## Delivery
+ manager (Manager)
+ recipient (Recipient)
+ pickup_at: `2016-01-01T18:00Z` (string, nullable)
+ deliver_at: `2016-01-01T19:00Z` (string)
+ instructions: `Please ring bell and wait, I am slow to answering the door. If I don’t answer within a few minutes the keysafe number is 9018. Please enter and announce loudly who you are.` (string)
+ route (Route)
+ order (Order)

## Route
+ destination (RoutePoint)
+ pickup (RoutePoint)

## RoutePoint
+ coordinates (Coordinates, optional)
+ address: `1239 Bartoletti Fords Suite 239` (string)

## Order
+ items (array[OrderItem]) - List of items to be delivered
+ purchased: `true` (boolean) - Client has already paid
+ payment: `true` (boolean) - Client have to pay directly to the driver

## OrderItem
+ title: `iPhone 7, 64GB, black` (string) - Item description
+ price: `1100` (number) - Price

## Job
+ delivery (Delivery)
+ driver (Driver)
+ signature_file (SignatureFile)
+ photos (array[Photo])
+ accepted_at: `2016-01-01T15:01:23Z` (string, nullable)
+ started_at: `2016-01-01T15:01:23Z` (string, nullable)
+ cancelled_at: `2016-01-01T15:01:23Z` (string, nullable)
+ completed_at: `2016-01-01T15:01:23Z` (string, nullable)
+ signed_at: `2016-01-01T15:01:23Z` (string, nullable)
+ reason_cancel (CancelReason, nullable)
+ notes: `My car is broken` (string, nullable)

## AcceptedJob (Job)
+ Include Job
+ signature_file (object, nullable)
+ photos (array, nullable)
+ accepted_at: `2016-01-01T15:01:23Z` (string, nullable)
+ started_at (string, nullable)
+ cancelled_at (string, nullable)
+ completed_at (string, nullable)
+ signed_at (string, nullable)
+ reason_cancel (string, nullable)
+ notes (string, nullable)

## StartedJob (Job)
+ Include Job
+ signature_file (object, nullable)
+ photos (array, nullable)
+ accepted_at: `2016-01-01T15:01:23Z` (string, nullable)
+ started_at: `2016-01-01T15:10:23Z` (string, nullable)
+ cancelled_at (string, nullable)
+ completed_at (string, nullable)
+ signed_at (string, nullable)
+ reason_cancel (string, nullable)
+ notes (string, nullable)

## CancelledJob (Job)
+ Include Job
+ signature_file (object, nullable)
+ photos (array, nullable)
+ accepted_at: `2016-01-01T15:01:23Z` (string)
+ started_at: `2016-01-01T15:10:23Z` (string)
+ cancelled_at: `2016-01-01T15:30:23Z` (string)
+ completed_at (string, nullable)
+ signed_at (string, nullable)
+ reason_cancel: `driver_fault` (CancelReason)
+ notes: `My car is broken` (string)

## CompletedJob (Job)
+ Include Job
+ signature_file (object, nullable)
+ photos (array, nullable)
+ accepted_at: `2016-01-01T15:01:23Z` (string, nullable)
+ started_at: `2016-01-01T15:10:23Z` (string, nullable)
+ cancelled_at (string, nullable)
+ completed_at: `2016-01-01T16:00:00Z` (string, nullable)
+ signed_at (string, nullable)
+ reason_cancel (string, nullable)
+ notes (string, nullable)

## SignedJob (Job)
+ Include Job
+ signature_file (object, nullable)
+ photos (array, nullable)
+ accepted_at: `2016-01-01T15:01:23Z` (string, nullable)
+ started_at: `2016-01-01T15:10:23Z` (string, nullable)
+ cancelled_at (string, nullable)
+ completed_at: `2016-01-01T16:00:00Z` (string, nullable)
+ signed_at: `2016-01-01T16:02:00Z` (string, nullable)
+ reason_cancel (string, nullable)
+ notes (string, nullable)

## SignatureFile
+ filename: `j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ url: `https://cdn.qwiqer.com/signatures/j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ created_at: `2016-01-01T15:01:23Z` (string)

## CancelReason (enum)
- driver_fault
- recipient_fault
- recipient_cancel

## Photo
+ filename: `j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ url: `https://cdn.qwiqer.com/signatures/j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ created_at: `2016-01-01T15:01:23Z` (string)

## User
+ email: `user@example.com` (string)
+ phone: `470.408.0187` (string)
+ first_name: `Hoyt` (string)
+ last_name: `Grimes` (string)

## Driver
+ id: `3` (string)
+ Include InviteDriverParams
+ coordinates (Coordinates)
+ status: `online` (string) - enum: [online, offline]

## InviteDriverParams
+ phone: `470.408.0187` (string)
+ first_name: `Hoyt` (string)
+ last_name: `Grimes` (string)

## Manager
+ id: `1` (string)
+ Include User

## Recipient
+ id: `2` (string)
+ phone: `470.408.0187` (string)
+ name: `John Smith` (string)
+ notes: `VIP client` (string)

## RecipientParams
+ phone: `470.408.0187` (string)
+ name: `John Smith` (string)
+ notes: `VIP client` (string)

## Comment
+ text: `I'm on my way. Can be a bit late because of traffic jams` (string)
+ author (User)

## Coordinates
+ latitude: 55.449667 (number)
+ longitude: 73.804010 (number)

## DriverStatus (enum)
- online
- offline

## NotFoundError
+ error: `Not Found` (string)

## UnprocessableEntityError
+ errors (object)
  + base: `Some basic error happened` (array, optional)
  + field: `Some field is invalid` (array, optional)

## Unauthorized
+ errors (object)
  + base: `You cannot perform this action.` (array)
