FORMAT: 1A
HOST: http://api.staging.qwiqer.com

# Core API V1.0

## Introduction
The Qwiqer API is organized around REST. Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, like HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients.

We support cross-origin resource sharing, allowing you to interact securely with our API from a client-side web application (though you should never expose your secret API key in any public website's client-side code). JSON is returned by all API responses, including errors, although our API libraries convert responses to appropriate language-specific objects.

To make the API as explorable as possible, accounts have test mode and live mode API keys. There is no "switch" for changing between modes, just use the appropriate key to perform a live or test transaction.

## Authentication
Authenticate your account when using the API by including your secret API key in the request. You can manage your API keys in the Dashboard. Your API keys carry many privileges, so be sure to keep them secret! Do not share your secret API keys in publicly accessible areas such GitHub, client-side code, and so forth.

Authentication to the API is performed via HTTP Basic Auth. Provide your API key as the basic auth username value. You do not need to provide a password.

If you need to authenticate via bearer auth (e.g., for a cross-origin request), use `-H "Authorization: Bearer test_BQokikJOvBiI2HlWgH4olfQ2"` instead of `-u test_BQokikJOvBiI2HlWgH4olfQ2:`.

All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.

# Group Deliveries

# Group Authenticate

## Login a manager [POST /login]
Authenticate manager

+ Attributes
    + auth (object)
        + email: `manager@example.com`
        + password: `12345678`

+ Request (application/json)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (object)
        + jwt (string)

## Collection [/deliveries]

### Retrieve all Deliveries [GET]
Returns all active deliveries.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Delivery])

### Create Delivery [POST]
Creates a delivery.

+ Request (application/json)
    + Attributes
      + Include Delivery
      + customer_id: `bc59e4f6-2fba-46ad-a71e-2535b4899061` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)
      + Include Delivery

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

## Delivery [/deliveries/{id}]

### Retrieve a delivery [GET]
Returns delivery.

+ Parameters
  + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)
      + Include Delivery

+ Response 404 (application/json)
    + Attributes (NotFoundError)

### Update a delivery [PUT]
Updates a delivery.

+ Parameters
  + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)
      + Include Delivery

+ Response 404 (application/json)
    + Attributes (NotFoundError)

# Group Jobs

## Collection [/jobs]

### Retrieve all Jobs [GET]
Returns all active jobs.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Delivery])

## Job [/jobs/{id}]

### Retrieve a job [GET]
Returns Job.

+ Parameters
  + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)
      + Include Job

## /jobs/{id}/start

### Start a job [POST]
Driver starts a job.

+ Parameters
    + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes
      + driver_id: `45860a5e-16da-4a78-b192-f024907484d2` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)
      + Include Job

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/cancel

### Cancel a job [POST]
Driver cancels a job.

+ Parameters
    + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes
      + reason (CancelReason)
      + comment: `Customer did not answer` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)
      + Include Job

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/complete

### Complete a job [POST]
Driver completes a job.

+ Parameters
    + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes
      + reason: `Customer did not answer` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)
      + Include Job

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

## /jobs/{id}/sign

### Sign a job [POST]
Driver signs a job.

+ Parameters
    + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes
      + signature_file (object)
        + data: `base64:image/png...` (string)

+ Response 200 (application/json)
    + Attributes
      + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)
      + Include Job

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

# Group Photos

## /jobs/{job_id}/photos

### Add a photo to a job [POST]
Driver adds a photo to a job.

+ Parameters
    + job_id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes
      + photo (object)
        + data: `base64:image/png...` (string)

+ Response 200 (application/json)
    + Attributes
      + Include Photo

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

### List all photos [GET]
Returns a list of job's photos.

+ Parameters
    + job_id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Response 200 (application/json)
    + Attributes (array[Photo])

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

# Group Comments

## /jobs/{job_id}/comments

### List all comments [GET]
Returns a list of job's comments.

+ Parameters
    + id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Response 200 (application/json)
    + Attributes (array[Comment])

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

### Add a comment to a job [POST]
Driver adds a comment to a job.

+ Parameters
    + job_id: `0fb13562-9faa-4370-be19-c6c6be59ff43` (string)

+ Request (application/json)
    + Attributes (Comment)

+ Response 200 (application/json)
    + Attributes
      + id: `fb4c54ff-60a6-4b76-9cce-7b279152a7b5` (string)
      + Include Comment

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

# Group Drivers

## /drivers

### List all drivers [GET]
Returns all available drivers.
"Available" means a driver signed up and uses mobile app despite the current status: online or offline.

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Driver])

### Invite a driver [POST]
Creates a driver.

+ Request (application/json)
    + Attributes
      + Include User

+ Response 200 (application/json)
    + Attributes (Driver)

+ Response 422 (application/json)
    + Attributes (UnprocessableEntityError)

## /drivers/{id}

### Retrieve a driver [GET]
Returns a driver.

+ Parameters
  + id: `19be888c-b731-4348-99f5-9bec1fc5a5ec` (string)

+ Response 200 (application/json)
    + Attributes (Driver)

+ Response 404 (application/json)
    + Attributes (NotFoundError)

# Data Structures

## Delivery
+ pickup_at: `2016-01-01T18:00Z` (string, nullable)
+ deliver_at: `2016-01-01T18:00Z` (string)
+ instructions: `Please ring bell and wait, I am slow to answering the door. If I don’t answer within a few minutes the keysafe number is 9018. Please enter and announce loudly who you are. I have a gun.` (string)
+ route (Route)
+ order (Order)

## Route
+ destination (RoutePoint)
+ pickup (RoutePoint)

## RoutePoint
+ coordinates (Coordinates)
+ address: `1239 Bartoletti Fords Suite 239` (string)

## Order
+ items (OrderItem) - List of items to be delivered
+ purchased: `true` (boolean) - Client has already paid
+ payment: `true` (boolean) - Client have to pay directly to the driver

## OrderItem
+ title: `iPhone 7, 64GB, black` (string) - Item description
+ price: `1100` (number) - Price

## Job
+ delivery (Delivery)
+ driver (Driver)
+ customer (Customer)
+ manager (Manager)
+ signature_file (SignatureFile)
+ photos (array[Photo])
+ started_at: `2016-01-01T15:01:23Z`
+ cancelled_at: `2016-01-01T15:01:23Z`
+ completed_at: `2016-01-01T15:01:23Z`
+ signed_at: `2016-01-01T15:01:23Z`
+ reason_cancel: `Customer did not answer` (string)

## SignatureFile
+ filename: `j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ url: `https://cdn.qwiqer.com/signatures/j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ created_at: `2016-01-01T15:01:23Z` (string)

## CancelReason (enum)
- driver_fault
- customer_fault
- customer_cancel

## Photo
+ filename: `j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ url: `https://cdn.qwiqer.com/signatures/j_f2b337f8-55db-40f9-b052-ce8210cac868.png` (string)
+ created_at: `2016-01-01T15:01:23Z` (string)

## User
+ email: `user@example.com` (string)
+ phone: `470.408.0187` (string)
+ first_name: `Hoyt` (string)
+ last_name: `Grimes` (string)

## Driver
+ id: `45860a5e-16da-4a78-b192-f024907484d2` (string)
+ Include User
+ coordinates (Coordinates)
+ status: `online` (DriverStatus)

## Manager
+ id: `04b4db1e-dd13-4395-8f1f-b1ea8cbba79a` (string)
+ Include User

## Customer
+ id: `bc59e4f6-2fba-46ad-a71e-2535b4899061` (string)
+ Include User

## Comment
+ text: `I'm on my way. Can be a bit late because of traffic jams` (string)
+ author (User)

## Coordinates
+ latitude: 55.449667 (number)
+ longitude: 73.804010 (number)

## DriverStatus (enum)
- online
- offline

## NotFoundError
+ error: `Not Found` (string)

## UnprocessableEntityError
+ errors (object)
  + base: `Some basic error happened` (array, optional)
  + field: `Some field is invalid` (array, optional)
